### PR TITLE
Add keynote page with just Anna on

### PR DESCRIPTION
**Pull request by alexchamberlain**
TODO/Needed
- I took Anna's picture from Twitter; we should ask her what picture she'd like us to us.
- Likewise, I made up a blurb just for layout purposes - we should ask Anna for a blurb.
- The schedule timings are copy & pasted from last year. Need to wait for confirmed workshops and double check our timing plans. IIRC lunch was too long last year?
- Investigate using Jekyll for the copy & paste templating.

### CODE REVIEW

**Comment by palvarez89** [comment]
I know it's a WIP, but did you forget to push `keynote.html` and `schedule.html` files?

**Comment by alexchamberlain** [comment]
@palvarez89 How embarrassing - fixed not.

**Comment by mariocj89** [comment]
Is this ready to land? Still in WIP though it seems you made some updates, also, do you have this published somewhere we can preview?

**Comment by alexchamberlain** [comment]
No, this is blocked by speaker bios atm. I've published sponsors to index.html today, and working on venue information atm.

**Comment by alexchamberlain** [comment]
This can be reviewed at https://alexchamberlain.github.io/pylondinium.github.io/keynote.html

**Pull request merged**
