### PR TITLE
Sketch out schedule.

### PR DESCRIPTION
**Pull request by alexchamberlain**
Sketch out schedule

TODO:
* [x] Clarify the order of keynote speakers.
* [x] Sketch out talk-level pages.
* [x] Clarify if we want to make any changes to running times.
* [x] Figure out when the Women In Tech panel will be @lkollar 
* [x] Figure out what order the talks should be in @lkollar - I think their currently pseudo random by author's name
* [x] Need metadata for _Hypothesis: Property-Based Testing for Python_

### CODE REVIEW

**Comment by alexchamberlain** [comment]
Latest draft @ https://alexchamberlain.github.io/pylondinium.github.io/

**Comment by lkollar** [comment]
The panel is scheduled for Saturday 15:50 to 16:50 as far as I know.

See the full schedule here: https://docs.google.com/spreadsheets/d/1KgWdji5yVIeuWZX0mFYww0K-O1U0wRdsGcLJ4HNrKx4/edit#gid=937424330

**Comment by lkollar** [comment]
I think the schedule and the talk detail pages look great. One thing I noticed is that the separator lines on the schedule table are not very visible. Something more contrasty would be better I think.

**Comment by alexchamberlain** [comment]
Demo @ https://alexchamberlain.github.io/pylondinium.github.io/ updated with latest changes.

@lkollar I've made some style changes to the schedule page to make the contrast better. @maigimenez what do you think about the use of red & bold?

**Pull request merged**
